[build-system]
requires = ["setuptools>=75"]
build-backend = "setuptools.build_meta"

[project]
name = "nulllauncher"
version = "1.11.8"
description = "Terminal Minecraft launcher for Windows"
requires-python = ">=3.10"
dependencies = [
  "minecraft-launcher-lib==8.0",
  "Pillow==12.3.0",
]

[project.scripts]
nulllauncher = "null_launcher.cli:main"

[tool.setuptools]
packages = ["null_launcher"]
